### ISSUE TITLE
Quesiton over paragraph regarding the receipt and spending of ZEP & external tokens.

### ISSUE THREAD

**Issue by roschler** [OpenZeppelin/whitepaper#3]
In Section 6.2 that describes the Buffer approach there is this sentence:

"The developer then receives ZEP and spends the external tokens."

This is a little confusing to me. Since the external tokens are described as belonging to the external protocol (Ether? ZCash?, etc.), the concept of receiving ZEP tokens and somehow spending the external tokens by spending the ZEP tokens is hard for me to grasp. Is the intent here to say that the developer, now that they have received ZEP tokens, is spending implicitly spending the external tokens by proxy where the proxy agent is the ZEP tokens? Without knowing the true intent here I can't suggest an alternate explanation.

**Comment by fiiiu** [comment]
This does not dwell on a potential implementation of this (i.e. need of proxys). What we say is that an agent will be responsible for providing this exchange service through a buffer of external tokens, that are spent when ZEP comes in to pay for a service.

**Comment by facuspagnuolo** [comment]
Considering the answer above, since there was no more activity, we are closing this issue. If there are any further questions please open a new one. Thanks!
